### ISSUE TITLE
Output sequence headers in format suitable for RepeatMasker

### ISSUE THREAD

**Issue by Neato-Nick** [Dfam-consortium/FamDB#1]
Hi,

RepeatMasker recently removed utility scripts to extract sequences from a library (queryRepeatDatabase.pl) and now relies on famdb. But, it doesn't look like famdb.py outputs repeats with FASTA headers that RepeatMasker can read as classified sequences. All the repeats are considered Unclassified when extracted using

`famdb.py families -f fasta_name `
or
`-f fasta_acc`

These human-readable formats are nice, but is it possible to add an output format for sequences to be understood by RepeatMasker? It takes headers in formats like this example:
`>ltr-1_family-2#LTR/Gypsy`

The tool that RepeatMasker recently removed outputted sequences with the according format. I am loving FamDB though, it is more flexible and capable in every other way.

**Comment by jebrosen** [comment]
> These human-readable formats are nice, but is it possible to add an output format for sequences to be understood by RepeatMasker? It takes headers in formats like this example:

Yes, this is already possible! RepeatMasker itself even uses the option internally: **`--include-class-in-name`**. Since the nomenclature is specific to RepeatMasker, I left it undocumented for now. I now think it would be more useful to include it in the help and the README; I'll keep this issue open as a reminder to fix that.

And thanks so much for pointing this out -- this difference slipped my mind when I updated the repeatmasker.help file.

**Comment by jebrosen** [comment]
I've updated or added to the help here and in RepeatMasker, and those changes will make it into the next releases of both programs. Thanks again!

**Comment by Neato-Nick** [comment]
Sounds like you had already tested that parameter but for what it's worth, I confirmed it works and RepeatMasker interprets the fasta headers perfectly. Thanks!
